# Generated by Django 5.2.17 on 2026-08-23 00:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-filled from the title. This becomes /projects/…', unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Shown under the title and in the projects grid.', max_length=300)),
                ('description', models.TextField(blank=True, help_text='A short introduction paragraph at the top of the page. Leave empty to hide it.')),
                ('hero_image', models.ImageField(upload_to='projects/')),
                ('show_workshops', models.BooleanField(default=True, help_text='Turn off if this project has no workshop recaps yet.')),
                ('show_film', models.BooleanField(default=False)),
                ('film_url', models.URLField(blank=True, help_text='A YouTube link, shown in the project film section.')),
                ('film_title', models.CharField(blank=True, max_length=200)),
                ('film_text', models.TextField(blank=True)),
                ('film_poster', models.ImageField(blank=True, null=True, upload_to='projects/film/')),
                ('show_interviews', models.BooleanField(default=True, help_text='Show interviews related to this project.')),
                ('show_social', models.BooleanField(default=True, help_text='Show Instagram highlights for this project.')),
                ('show_closing_cta', models.BooleanField(default=True, help_text='Show the closing "Join the conversation" block.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('related_interviews', models.ManyToManyField(blank=True, related_name='related_projects', to='interviews.interview')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectClosingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_links', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctas', to='projects.project')),
            ],
            options={
                'verbose_name': 'CTA button',
                'verbose_name_plural': 'CTA buttons',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-filled from the title.', unique=True)),
                ('image', models.ImageField(upload_to='workshops/')),
                ('date_label', models.CharField(help_text='e.g. "October 2025"', max_length=100)),
                ('excerpt', models.TextField(help_text='One or two lines, shown on the project page.')),
                ('body', ckeditor.fields.RichTextField(help_text="The full recap text, shown on the workshop's own page.")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='projects.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
