# Generated by Django 5.2.17 on 2026-08-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, choices=[('volunteer', 'Volunteer'), ('donations', 'Donations'), ('food', 'Food Support'), ('education', 'Education Support'), ('medical', 'Medical Support'), ('sports', 'Sports Support')], max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Landscape photo, at least 1600px wide.', upload_to='hero/')),
                ('eyebrow', models.CharField(help_text='Small line above the title, e.g. the date and place of an event.', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(help_text='One or two sentences.', max_length=300)),
                ('cta_label', models.CharField(default='Learn more', help_text='Text on the button, e.g. "Register now".', max_length=50)),
                ('cta_link', models.CharField(blank=True, help_text='Where the button goes, e.g. /projects or a full URL.', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True, help_text='Untick to hide this slide without deleting it.')),
            ],
            options={
                'verbose_name': 'Hero slide',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='info@douri.lu', max_length=254)),
                ('phone', models.CharField(default='+(352) 661 158300', max_length=50)),
                ('address', models.TextField(default="108, Route d'Esch, L-4450 Belvaux, Sanem, Luxembourg")),
                ('rcs', models.CharField(default='R.C.S Luxembourg F12823', max_length=100, verbose_name='Registration number')),
                ('iban', models.CharField(default='LU00 0000 0000 0000 0000', help_text='Shown on the Support Us page with a copy button.', max_length=50)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/Douri.asbl', verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/douri.asbl', verbose_name='Instagram')),
                ('footer_text', models.TextField(default='Join us on this journey of unity, expression and advocacy, as we strive to transcend boundaries, celebrate diversity and embrace the essence of humanity.')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
