# Generated by Django 5.2.17 on 2026-08-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaFeatured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='agenda/')),
                ('description', models.TextField()),
                ('participants', models.TextField(help_text='One per line, e.g. "Exhibition: Name1, Name2"')),
                ('date_label', models.CharField(max_length=150, verbose_name='Date')),
                ('location', models.CharField(max_length=250)),
                ('entry', models.CharField(blank=True, default='Free entry — registration required', max_length=150)),
                ('register_url', models.URLField(help_text='A Google Form link works fine.', verbose_name='Registration link')),
                ('active', models.BooleanField(default=True, help_text='Untick when the event is over.')),
            ],
            options={
                'verbose_name': 'Featured event',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AgendaRecurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agenda/')),
                ('title', models.CharField(default='', max_length=200)),
                ('time_label', models.CharField(help_text='e.g. "15:00 – 16:30"', max_length=100, verbose_name='Time')),
                ('description', models.TextField()),
                ('dates_label', models.CharField(help_text='Separate with a dot or a dash.', max_length=250, verbose_name='All dates')),
                ('location', models.CharField(max_length=250)),
                ('price_tiers', models.CharField(max_length=250, verbose_name='Prices')),
                ('languages', models.CharField(max_length=150)),
                ('info_url', models.URLField(blank=True, help_text='Often an Instagram video.', verbose_name='Info link')),
                ('register_url', models.URLField(verbose_name='Registration link')),
                ('month', models.CharField(help_text='e.g. "March 2026" — decides where this appears on the page.', max_length=20)),
                ('date_label', models.CharField(blank=True, max_length=100, verbose_name='Date shown')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Recurring workshop',
                'ordering': ['month', 'order', 'id'],
            },
        ),
    ]
