# Generated by Django 5.2.17 on 2026-08-23 00:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('url', models.URLField(blank=True, verbose_name='Website')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=200)),
                ('photo', models.ImageField(help_text='A square photo works best.', upload_to='team/')),
                ('short_bio', models.CharField(help_text='One line, used on the homepage.', max_length=300)),
                ('full_bio', ckeditor.fields.RichTextField(help_text='The longer biography shown on the Our Team page.')),
                ('social_url', models.URLField(blank=True, verbose_name='Profile link')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
