# Generated by Django 5.2.17 on 2026-08-23 00:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Internal title. If left empty, the quote is used.', max_length=250)),
                ('slug', models.SlugField(blank=True, help_text='Auto-filled from the subject name.', unique=True)),
                ('subject_name', models.CharField(max_length=150, verbose_name='Person interviewed')),
                ('quote', models.CharField(help_text='The headline quote, used as the page title.', max_length=300)),
                ('prepared_by', models.CharField(blank=True, max_length=200)),
                ('edited_by', models.CharField(blank=True, max_length=200)),
                ('hero_image', models.ImageField(upload_to='interviews/')),
                ('body', ckeditor.fields.RichTextField(help_text='The full interview text.')),
                ('publish_date', models.DateField()),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
