# Generated by Django 5.2.17 on 2026-08-23 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='instagram/', verbose_name='Screenshot')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='What the post is about')),
                ('post_url', models.URLField(verbose_name='Instagram link')),
                ('featured_on_home', models.BooleanField(default=False, verbose_name='Show in the homepage strip')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_highlights', to='projects.project')),
            ],
            options={
                'verbose_name': 'Instagram post',
                'ordering': ['order', '-id'],
            },
        ),
    ]
